// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1WWukWY7Z2HKyjkqAAQSFb6ifj_8Qj2o',
    appId: '1:618923876330:web:80062316d300f52d389c93',
    messagingSenderId: '618923876330',
    projectId: 'plant-app-30887',
    authDomain: 'plant-app-30887.firebaseapp.com',
    storageBucket: 'plant-app-30887.firebasestorage.app',
    measurementId: 'G-005ZEJVLHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2_sSiO1-x8vceEZNNFJgMXZgu_RWIq0',
    appId: '1:618923876330:android:c0e2292e9666ab7e389c93',
    messagingSenderId: '618923876330',
    projectId: 'plant-app-30887',
    storageBucket: 'plant-app-30887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJY3RITEH3h6b2eRkZVyTkrvaDEF-h6Q',
    appId: '1:618923876330:ios:3852a8f62762b2f0389c93',
    messagingSenderId: '618923876330',
    projectId: 'plant-app-30887',
    storageBucket: 'plant-app-30887.firebasestorage.app',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJY3RITEH3h6b2eRkZVyTkrvaDEF-h6Q',
    appId: '1:618923876330:ios:3852a8f62762b2f0389c93',
    messagingSenderId: '618923876330',
    projectId: 'plant-app-30887',
    storageBucket: 'plant-app-30887.firebasestorage.app',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1WWukWY7Z2HKyjkqAAQSFb6ifj_8Qj2o',
    appId: '1:618923876330:web:408117739b45a925389c93',
    messagingSenderId: '618923876330',
    projectId: 'plant-app-30887',
    authDomain: 'plant-app-30887.firebaseapp.com',
    storageBucket: 'plant-app-30887.firebasestorage.app',
    measurementId: 'G-6RPG7F0CZ4',
  );
}
